[project]
name = 'tic-tac-toe'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.lending-pool-v2]
path = 'contracts/lending-pool-v2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.tic-tac-toe-v2]
path = 'contracts/tic-tac-toe.clar'
clarity_version = 3
epoch = 'latest'
depends_on = ['lending-pool-v2']

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'